#!/usr/bin/env python3
"""
CUDA Memory Access Pattern Plotter

This script reads the output files generated by the CUDA memory benchmark
and creates plots showing memory access pattern performance.
"""

import matplotlib.pyplot as plt
import numpy as np
import os
import glob
import argparse
from pathlib import Path

def read_benchmark_file(filename):
    """
    Read benchmark data from a text file.
    Returns arrays of offsets/strides and corresponding bandwidths.
    """
    if not os.path.exists(filename):
        print(f"Warning: File {filename} not found")
        return None, None
    
    offsets_or_strides = []
    bandwidths = []
    
    try:
        with open(filename, 'r') as f:
            for line in f:
                line = line.strip()
                # Skip comments and empty lines
                if line.startswith('#') or not line:
                    continue
                
                # Parse CSV format: offset/stride, bandwidth
                parts = line.split(',')
                if len(parts) >= 2:
                    try:
                        offset_or_stride = int(parts[0].strip())
                        bandwidth = float(parts[1].strip())
                        offsets_or_strides.append(offset_or_stride)
                        bandwidths.append(bandwidth)
                    except ValueError:
                        continue
    except Exception as e:
        print(f"Error reading {filename}: {e}")
        return None, None
    
    return np.array(offsets_or_strides), np.array(bandwidths)

def plot_offset_analysis(precision='single', save_plots=True, show_plots=True):
    """
    Plot offset analysis for different memory types.
    """
    plt.figure(figsize=(12, 8))
    
    # Define memory types and their plotting styles
    memory_types = {
        'Pageable': {'marker': 'o', 'linestyle': '-', 'color': 'blue'},
        'Pinned': {'marker': 's', 'linestyle': '-', 'color': 'red'}
    }
    
    plotted_any = False
    
    for mem_type, style in memory_types.items():
        filename = f"offset_{precision}_{mem_type}.txt"
        offsets, bandwidths = read_benchmark_file(filename)
        
        if offsets is not None and bandwidths is not None:
            plt.plot(offsets, bandwidths, 
                    marker=style['marker'], 
                    linestyle=style['linestyle'],
                    color=style['color'],
                    markersize=6,
                    linewidth=2,
                    label=f'{mem_type} Memory')
            plotted_any = True
    
    if plotted_any:
        plt.xlabel('Offset (elements)', fontsize=12)
        plt.ylabel('Effective Bandwidth (GB/s)', fontsize=12)
        plt.title(f'Effective Bandwidth vs. Offset for {precision.title()} Precision', fontsize=14)
        plt.grid(True, alpha=0.3)
        plt.legend(fontsize=11)
        plt.xlim(0, 32)
        
        # Set reasonable y-axis limits
        plt.ylim(0, None)
        
        # Add some styling
        plt.tight_layout()
        
        if save_plots:
            plt.savefig(f'offset_analysis_{precision}.png', dpi=300, bbox_inches='tight')
            print(f"Offset analysis plot saved as offset_analysis_{precision}.png")
        
        if show_plots:
            plt.show()
    else:
        print(f"No data found for offset analysis ({precision} precision)")
        plt.close()

def plot_stride_analysis(precision='single', save_plots=True, show_plots=True):
    """
    Plot stride analysis for different memory types.
    """
    plt.figure(figsize=(12, 8))
    
    # Define memory types and their plotting styles
    memory_types = {
        'Pageable': {'marker': 'o', 'linestyle': '-', 'color': 'blue'},
        'Pinned': {'marker': 's', 'linestyle': '-', 'color': 'red'}
    }
    
    plotted_any = False
    
    for mem_type, style in memory_types.items():
        filename = f"stride_{precision}_{mem_type}.txt"
        strides, bandwidths = read_benchmark_file(filename)
        
        if strides is not None and bandwidths is not None:
            plt.plot(strides, bandwidths, 
                    marker=style['marker'], 
                    linestyle=style['linestyle'],
                    color=style['color'],
                    markersize=6,
                    linewidth=2,
                    label=f'{mem_type} Memory')
            plotted_any = True
    
    if plotted_any:
        plt.xlabel('Stride (elements)', fontsize=12)
        plt.ylabel('Effective Bandwidth (GB/s)', fontsize=12)
        plt.title(f'Effective Bandwidth vs. Stride for {precision.title()} Precision', fontsize=14)
        plt.grid(True, alpha=0.3)
        plt.legend(fontsize=11)
        plt.xlim(1, 32)
        
        # Set reasonable y-axis limits
        plt.ylim(0, None)
        
        # Add some styling
        plt.tight_layout()
        
        if save_plots:
            plt.savefig(f'stride_analysis_{precision}.png', dpi=300, bbox_inches='tight')
            print(f"Stride analysis plot saved as stride_analysis_{precision}.png")
        
        if show_plots:
            plt.show()
    else:
        print(f"No data found for stride analysis ({precision} precision)")
        plt.close()

def plot_comparison(precision='single', save_plots=True, show_plots=True):
    """
    Create a comparison plot showing both offset and stride analysis side by side.
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
    
    # Define memory types and their plotting styles
    memory_types = {
        'Pageable': {'marker': 'o', 'linestyle': '-', 'color': 'blue'},
        'Pinned': {'marker': 's', 'linestyle': '-', 'color': 'red'}
    }
    
    # Plot offset analysis
    plotted_offset = False
    for mem_type, style in memory_types.items():
        filename = f"offset_{precision}_{mem_type}.txt"
        offsets, bandwidths = read_benchmark_file(filename)
        
        if offsets is not None and bandwidths is not None:
            ax1.plot(offsets, bandwidths, 
                    marker=style['marker'], 
                    linestyle=style['linestyle'],
                    color=style['color'],
                    markersize=6,
                    linewidth=2,
                    label=f'{mem_type} Memory')
            plotted_offset = True
    
    if plotted_offset:
        ax1.set_xlabel('Offset (elements)', fontsize=12)
        ax1.set_ylabel('Effective Bandwidth (GB/s)', fontsize=12)
        ax1.set_title('Misaligned Data Accesses', fontsize=14)
        ax1.grid(True, alpha=0.3)
        ax1.legend(fontsize=11)
        ax1.set_xlim(0, 32)
        ax1.set_ylim(0, None)
    
    # Plot stride analysis
    plotted_stride = False
    for mem_type, style in memory_types.items():
        filename = f"stride_{precision}_{mem_type}.txt"
        strides, bandwidths = read_benchmark_file(filename)
        
        if strides is not None and bandwidths is not None:
            ax2.plot(strides, bandwidths, 
                    marker=style['marker'], 
                    linestyle=style['linestyle'],
                    color=style['color'],
                    markersize=6,
                    linewidth=2,
                    label=f'{mem_type} Memory')
            plotted_stride = True
    
    if plotted_stride:
        ax2.set_xlabel('Stride (elements)', fontsize=12)
        ax2.set_ylabel('Effective Bandwidth (GB/s)', fontsize=12)
        ax2.set_title('Strided Memory Access', fontsize=14)
        ax2.grid(True, alpha=0.3)
        ax2.legend(fontsize=11)
        ax2.set_xlim(1, 32)
        ax2.set_ylim(0, None)
    
    if plotted_offset or plotted_stride:
        plt.suptitle(f'Memory Access Pattern Analysis - {precision.title()} Precision', fontsize=16)
        plt.tight_layout()
        
        if save_plots:
            plt.savefig(f'memory_access_comparison_{precision}.png', dpi=300, bbox_inches='tight')
            print(f"Comparison plot saved as memory_access_comparison_{precision}.png")
        
        if show_plots:
            plt.show()
    else:
        print(f"No data found for comparison plot ({precision} precision)")
        plt.close()

def list_available_files():
    """
    List all available benchmark files in the current directory.
    """
    offset_files = glob.glob("offset_*.txt")
    stride_files = glob.glob("stride_*.txt")
    
    print("Available benchmark files:")
    print("Offset files:", offset_files)
    print("Stride files:", stride_files)
    
    return offset_files, stride_files

def main():
    parser = argparse.ArgumentParser(description='Plot CUDA memory access pattern benchmarks')
    parser.add_argument('--precision', choices=['single', 'double'], default='single',
                        help='Precision type to plot (default: single)')
    parser.add_argument('--plot-type', choices=['offset', 'stride', 'comparison', 'all'], 
                        default='all', help='Type of plot to generate (default: all)')
    parser.add_argument('--no-save', action='store_true', 
                        help='Do not save plots to files')
    parser.add_argument('--no-show', action='store_true', 
                        help='Do not display plots on screen')
    parser.add_argument('--list-files', action='store_true',
                        help='List available benchmark files')
    
    args = parser.parse_args()
    
    if args.list_files:
        list_available_files()
        return
    
    save_plots = not args.no_save
    show_plots = not args.no_show
    
    # Set matplotlib backend for better compatibility
    if not show_plots:
        plt.switch_backend('Agg')
    
    print(f"Plotting {args.precision} precision results...")
    
    if args.plot_type in ['offset', 'all']:
        plot_offset_analysis(args.precision, save_plots, show_plots)
    
    if args.plot_type in ['stride', 'all']:
        plot_stride_analysis(args.precision, save_plots, show_plots)
    
    if args.plot_type in ['comparison', 'all']:
        plot_comparison(args.precision, save_plots, show_plots)
    
    print("Plotting complete!")

if __name__ == "__main__":
    main()
